### ISSUE TITLE
Install problem while make

### ISSUE THREAD

**Issue by LeileiCui** [fritzsedlazeck/SURVIVOR_ant#1]
Hi, Fritz!

Tks for this nice software, just met a problem when I tried to "make", any suggestions about it?

....
Linking C static library libz.a
[ 55%] Built target zlibstatic
Scanning dependencies of target survivor_ant
[ 59%] Building CXX object src/CMakeFiles/survivor_ant.dir/tree/IntervallTree.cpp.o
[ 62%] Building CXX object src/CMakeFiles/survivor_ant.dir/SURVIVOR_ant.cpp.o
[ 66%] Building CXX object src/CMakeFiles/survivor_ant.dir/Parser/BEDParser.cpp.o
[ 70%] Building CXX object src/CMakeFiles/survivor_ant.dir/Parser/GFFParser.cpp.o
[ 74%] Building CXX object src/CMakeFiles/survivor_ant.dir/Parser/VCFParser.cpp.o
[ 77%] Building CXX object src/CMakeFiles/survivor_ant.dir/print/VCFPrinter.cpp.o
In file included from bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp:8:
bin/11-SURVIVOR_ant/src/print/VCFPrinter.h: In member function 'void VCFPrinter::close_file()':
bin/11-SURVIVOR_ant/src/print/VCFPrinter.h:38: error: 'fclose' was not declared in this scope
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp: In member function 'void VCFPrinter::print_header(std::string)':
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp:45: error: 'fprintf' was not declared in this scope
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp: In member function 'void VCFPrinter::init()':
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp:98: error: 'fopen' was not declared in this scope
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp: In member function 'void VCFPrinter::print_orig_entry(SVS_Node*, int, std::pair<int, int>&)':
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp:176: error: 'fprintf' was not declared in this scope
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp:184: error: 'fprintf' was not declared in this scope
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp: In member function 'void VCFPrinter::print_entry(SVS_Node*, int, std::pair<int, int>&)':
bin/11-SURVIVOR_ant/src/print/VCFPrinter.cpp:274: error: 'fprintf' was not declared in this scope
make[2]: *** [src/CMakeFiles/survivor_ant.dir/print/VCFPrinter.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/survivor_ant.dir/all] Error 2
make: *** [all] Error 2

Best,
Leilei

**Comment by fritzsedlazeck** [comment]
Hi Leilei,
thanks for letting me know. I have fixed the code. You will need to download it again. 
Let me know if something else pops up. 
Thanks
Fritz

**Comment by LeileiCui** [comment]
Tks for this quick reply, Fritz! The SURVIVOR_ant could be installed perfectly now. 

Moreover, I still remember your amazing presentation about several softwares for SV calling and merge in UCL, and I just wonder is that fine for you to share that slide with me for further learning?

Best,
Leilei

**Comment by fritzsedlazeck** [comment]
Hi Leilei,
I can send you some slides from the UCL talk. Ping me at: fritz.sedlazeck@gmail.com
Thanks
Fritz
