### ISSUE TITLE
Looking for a good .bed or .gff annonation file for hg19

### ISSUE THREAD

**Issue by TendoLiu** [fritzsedlazeck/SURVIVOR_ant#10]
Hi Guys,
   I am having difficulty looking for a usable annotation files. Could anyone share?

Thanks

**Comment by fritzsedlazeck** [comment]
just to make sure, you cannot find a GFF file for a human genome hg19?
cheers
Fritz

**Comment by TendoLiu** [comment]
Hi Fritz,
   Thanks for the reply. I used UCSC hg19 reference genome to do the alignment. But I cannot find a good gff or bed annotation file anywhere. Do you have good resources?  I would be more than grateful.

Tendo

**Comment by fritzsedlazeck** [comment]
Ah, yeah that is always a pain.. 
I dont have one at hand, but here is a thread:
http://seqanswers.com/forums/showthread.php?t=32232

Cheers
Fritz
