### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by TendoLiu** [fritzsedlazeck/SURVIVOR_ant#11]
Code:

vcf1=Lumpy.vcf
vcf2=Delly.vcf
vcf3=Manta.vcf

$SurvivorPath/survivor_ant \
> -o combined.vcf \
> -l 20 \
> -v $vcf3 $vcf2 $vcf1 \
> -i $vcf1 \
> -b $hg19_geneANT

Output: PARSE ERROR:  Argument: Delly.vcf
             Couldn't find match for argument

The error info is two ambiguous to understand.

Thanks

**Comment by TendoLiu** [comment]
Use only required options
$SurvivorPath/survivor_ant \
> -i $vcf1

Running: 
INITIALIZE VCF:
Parse VCF: 0
Parse BED: 0
Parse GFF: 0
PRint:
start printing
print entries

Error:
Segmentation fault (core dumped)

**Comment by fritzsedlazeck** [comment]
can you open and read the delly.vcf or is it a compressed file?

**Comment by fritzsedlazeck** [comment]
and are these files in the directory you are executing it from ?

**Comment by TendoLiu** [comment]
`cd /bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVcompare/VCFs
hg19_geneANT=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/module/RefenceFiles/hg19/UCSC_hg19_geneAnnotation
SurvivorPath=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/module/SVcompare/SURVIVOR_ant/bin/survivor_ant-core-0.1.0

vcf1=Lumpy.vcf
vcf2=Delly.vcf
vcf3=Manta.vcf

$SurvivorPath/survivor_ant \
-o combined.vcf \
-l 20 \
-v $vcf3 $vcf2 $vcf1 \
-i $vcf1 `
Yes. The vcf files are not compressed and they are in the working directory.
I am executing survivor_ant from a different path.

Thanks,
Tendo

**Comment by TendoLiu** [comment]
bash-4.2$ cd /bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVcompare/VCFs
bash-4.2$ ls
Delly.vcf  Lumpy.vcf  Manta.vcf

Pretty sure the vcf files looks good. They are outputs from other well-known SV callers. Not even one of them could work. Any clues what could be the mistake?

Best wishes,
Tendo
